const shoes = [
  // Nike Collection
  {
    id: 1,
    name: "Nike Air Max 270",
    brand: "Nike",
    category: "Running",
    price: 150.99,
    rating: 4.8,
    reviews: 2345,
    color: "Black/White",
    sizes: [7, 7.5, 8, 8.5, 9, 9.5, 10, 10.5, 11, 12],
    inStock: true,
    discount: 15,
    featured: true,
    image: "https://static.nike.com/a/images/t_PDP_864_v1/f_auto,b_rgb:f5f5f5/q1g0h3p5v8q9k6l2m1n0/air-max-270-mens-shoes.png",
    imageGallery: [
      "https://static.nike.com/a/images/t_PDP_864_v1/f_auto,b_rgb:f5f5f5/air-max-270-side.jpg",
      "https://static.nike.com/a/images/t_PDP_864_v1/f_auto,b_rgb:f5f5f5/air-max-270-top.jpg",
      "https://static.nike.com/a/images/t_PDP_864_v1/f_auto,b_rgb:f5f5f5/air-max-270-back.jpg"
    ],
    description: "The Nike Air Max 270 delivers visible air cushioning and a sleek design inspired by Air Max icons.",
    material: "Mesh/Synthetic",
    weight: "320g",
    releaseDate: "2023-06-15",
    tags: ["running", "air-max", "cushioned"]
  },
  {
    id: 2,
    name: "Nike Air Force 1 '07",
    brand: "Nike",
    category: "Casual",
    price: 110.99,
    rating: 4.9,
    reviews: 5678,
    color: "White/White",
    sizes: [6, 6.5, 7, 7.5, 8, 8.5, 9, 9.5, 10, 10.5, 11, 12, 13],
    inStock: true,
    discount: 0,
    featured: true,
    image: "https://static.nike.com/a/images/t_PDP_864_v1/f_auto,b_rgb:f5f5f5/af1-07-mens-shoes.png",
    imageGallery: [
      "https://static.nike.com/a/images/t_PDP_864_v1/f_auto,b_rgb:f5f5f5/af1-white-side.jpg",
      "https://static.nike.com/a/images/t_PDP_864_v1/f_auto,b_rgb:f5f5f5/af1-white-top.jpg"
    ],
    description: "The radiance lives on in the Nike Air Force 1 '07, the b-ball icon that puts a fresh spin on what you know best.",
    material: "Leather",
    weight: "400g",
    releaseDate: "2023-01-20",
    tags: ["basketball", "classic", "leather"]
  },
  {
    id: 3,
    name: "Nike React Infinity Run Flyknit 3",
    brand: "Nike",
    category: "Running",
    price: 160.99,
    rating: 4.7,
    reviews: 1456,
    color: "Blue/Orange",
    sizes: [8, 8.5, 9, 9.5, 10, 10.5, 11, 12],
    inStock: false,
    discount: 10,
    featured: false,
    image: "https://static.nike.com/a/images/t_PDP_864_v1/f_auto,b_rgb:f5f5f5/react-infinity-run-flyknit-3-mens-road-running-shoes.png",
    description: "The Nike React Infinity Run Flyknit 3 is designed to help reduce injury and keep you running.",
    material: "Flyknit/React Foam",
    weight: "290g",
    releaseDate: "2023-09-10",
    tags: ["running", "flyknit", "stability"]
  },

  // Adidas Collection
  {
    id: 4,
    name: "Adidas Ultraboost 22",
    brand: "Adidas",
    category: "Running",
    price: 190.99,
    rating: 4.8,
    reviews: 3456,
    color: "Black/White",
    sizes: [7, 8, 9, 10, 11, 12],
    inStock: true,
    discount: 20,
    featured: true,
    image: "https://assets.adidas.com/images/h_840,f_auto,q_auto,fl_lossy,c_fill,g_auto/ultraboost-22-shoes.jpg",
    imageGallery: [
      "https://assets.adidas.com/images/ultraboost-22-side.jpg",
      "https://assets.adidas.com/images/ultraboost-22-top.jpg"
    ],
    description: "Ultraboost 22 shoes offer maximum energy return with every stride.",
    material: "Primeknit/Boost",
    weight: "310g",
    releaseDate: "2023-03-05",
    tags: ["running", "boost", "premium"]
  },
  {
    id: 5,
    name: "Adidas Stan Smith",
    brand: "Adidas",
    category: "Casual",
    price: 85.99,
    rating: 4.6,
    reviews: 7890,
    color: "White/Green",
    sizes: [6, 7, 8, 9, 10, 11, 12],
    inStock: true,
    discount: 0,
    featured: true,
    image: "https://assets.adidas.com/images/h_840,f_auto,q_auto,fl_lossy,c_fill,g_auto/stan-smith-shoes.jpg",
    description: "The iconic Stan Smith shoes feature a clean leather upper and classic perforated 3-Stripes.",
    material: "Leather",
    weight: "350g",
    releaseDate: "2023-02-14",
    tags: ["tennis", "classic", "minimalist"]
  },
  {
    id: 6,
    name: "Adidas NMD_R1",
    brand: "Adidas",
    category: "Lifestyle",
    price: 130.99,
    rating: 4.5,
    reviews: 2341,
    color: "Grey/Red",
    sizes: [8, 9, 10, 11],
    inStock: true,
    discount: 25,
    featured: false,
    image: "https://assets.adidas.com/images/nmd-r1-shoes.jpg",
    description: "The NMD_R1 combines streetwear style with Boost technology for all-day comfort.",
    material: "Mesh/Boost",
    weight: "330g",
    releaseDate: "2023-07-22",
    tags: ["urban", "boost", "streetwear"]
  },

  // Jordan Collection
  {
    id: 7,
    name: "Air Jordan 1 Retro High OG",
    brand: "Jordan",
    category: "Basketball",
    price: 180.99,
    rating: 4.9,
    reviews: 4567,
    color: "Chicago Red/Black/White",
    sizes: [7, 8, 9, 10, 11, 12, 13],
    inStock: false,
    discount: 0,
    featured: true,
    image: "https://static.nike.com/a/images/t_PDP_864_v1/f_auto,b_rgb:f5f5f5/air-jordan-1-retro-high-og-shoes.png",
    description: "The Air Jordan 1 Retro High OG brings back the shoe that started it all.",
    material: "Leather",
    weight: "420g",
    releaseDate: "2023-05-30",
    tags: ["basketball", "retro", "limited"]
  },
  {
    id: 8,
    name: "Air Jordan 4 Retro",
    brand: "Jordan",
    category: "Basketball",
    price: 210.99,
    rating: 4.8,
    reviews: 3124,
    color: "Military Black",
    sizes: [8, 9, 10, 11, 12],
    inStock: true,
    discount: 5,
    featured: true,
    image: "https://static.nike.com/a/images/t_PDP_864_v1/f_auto,b_rgb:f5f5f5/air-jordan-4-retro-shoes.png",
    description: "The Air Jordan 4 Retro features premium materials and iconic design elements.",
    material: "Leather/Mesh",
    weight: "410g",
    releaseDate: "2023-08-18",
    tags: ["basketball", "classic", "premium"]
  },

  // New Balance Collection
  {
    id: 9,
    name: "New Balance 990v5",
    brand: "New Balance",
    category: "Running",
    price: 175.99,
    rating: 4.7,
    reviews: 1890,
    color: "Grey",
    sizes: [7, 8, 9, 10, 11, 12, 13],
    inStock: true,
    discount: 10,
    featured: true,
    image: "https://nb.com/media/images/990v5-grey-shoes.jpg",
    description: "The 990v5 is the latest iteration of the iconic 990 series, made in USA.",
    material: "Suede/Mesh",
    weight: "380g",
    releaseDate: "2023-04-12",
    tags: ["running", "made-in-usa", "classic"]
  },
  {
    id: 10,
    name: "New Balance 327",
    brand: "New Balance",
    category: "Lifestyle",
    price: 100.99,
    rating: 4.5,
    reviews: 2234,
    color: "Red/White/Blue",
    sizes: [6, 7, 8, 9, 10, 11],
    inStock: true,
    discount: 30,
    featured: false,
    image: "https://nb.com/media/images/327-red-shoes.jpg",
    description: "The 327 reimagines classic 70s running shoes with modern style.",
    material: "Nylon/Suede",
    weight: "340g",
    releaseDate: "2023-10-05",
    tags: ["vintage", "trending", "lifestyle"]
  },

  // Puma Collection
  {
    id: 11,
    name: "Puma Suede Classic",
    brand: "Puma",
    category: "Casual",
    price: 65.99,
    rating: 4.6,
    reviews: 3451,
    color: "Black",
    sizes: [6, 7, 8, 9, 10, 11, 12],
    inStock: true,
    discount: 20,
    featured: true,
    image: "https://images.puma.com/images/suede-classic-black.jpg",
    description: "The Puma Suede Classic is a timeless icon that never goes out of style.",
    material: "Suede",
    weight: "360g",
    releaseDate: "2023-01-30",
    tags: ["suede", "classic", "streetwear"]
  },
  {
    id: 12,
    name: "Puma RS-X³",
    brand: "Puma",
    category: "Lifestyle",
    price: 110.99,
    rating: 4.4,
    reviews: 1237,
    color: "White/Blue/Red",
    sizes: [8, 9, 10, 11],
    inStock: true,
    discount: 15,
    featured: false,
    image: "https://images.puma.com/images/rs-x3-white.jpg",
    description: "The RS-X³ features chunky silhouettes and bold color combinations.",
    material: "Mesh/Leather",
    weight: "400g",
    releaseDate: "2023-11-18",
    tags: ["chunky", "retro", "bold"]
  },

  // Vans Collection
  {
    id: 13,
    name: "Vans Old Skool",
    brand: "Vans",
    category: "Skateboarding",
    price: 60.99,
    rating: 4.8,
    reviews: 8912,
    color: "Black/White",
    sizes: [5, 6, 7, 8, 9, 10, 11, 12, 13],
    inStock: true,
    discount: 0,
    featured: true,
    image: "https://images.vans.com/images/old-skool-black.jpg",
    description: "The Vans Old Skool is a classic skate shoe with the iconic side stripe.",
    material: "Canvas/Suede",
    weight: "320g",
    releaseDate: "2023-02-01",
    tags: ["skate", "classic", "canvas"]
  },
  {
    id: 14,
    name: "Vans Sk8-Hi",
    brand: "Vans",
    category: "Skateboarding",
    price: 70.99,
    rating: 4.7,
    reviews: 4562,
    color: "Black/White",
    sizes: [6, 7, 8, 9, 10, 11, 12],
    inStock: true,
    discount: 10,
    featured: false,
    image: "https://images.vans.com/images/sk8-hi-black.jpg",
    description: "The Sk8-Hi adds ankle support to the classic Vans design.",
    material: "Canvas/Suede",
    weight: "380g",
    releaseDate: "2023-03-22",
    tags: ["high-top", "skate", "classic"]
  },

  // ASICS Collection
  {
    id: 15,
    name: "ASICS Gel-Kayano 29",
    brand: "ASICS",
    category: "Running",
    price: 160.99,
    rating: 4.8,
    reviews: 2134,
    color: "Blue/White",
    sizes: [7, 8, 9, 10, 11, 12],
    inStock: true,
    discount: 15,
    featured: true,
    image: "https://images.asics.com/images/gel-kayano-29-blue.jpg",
    description: "The Gel-Kayano 29 provides premium stability and comfort for long runs.",
    material: "Mesh/Gel",
    weight: "310g",
    releaseDate: "2023-05-08",
    tags: ["stability", "running", "gel"]
  },
  {
    id: 16,
    name: "ASICS Gel-Lyte III",
    brand: "ASICS",
    category: "Lifestyle",
    price: 120.99,
    rating: 4.6,
    reviews: 1789,
    color: "Sand/Beige",
    sizes: [8, 9, 10, 11],
    inStock: false,
    discount: 25,
    featured: false,
    image: "https://images.asics.com/images/gel-lyte-iii-sand.jpg",
    description: "The Gel-Lyte III features the iconic split tongue design.",
    material: "Suede/Mesh",
    weight: "330g",
    releaseDate: "2023-09-14",
    tags: ["split-tongue", "retro", "lifestyle"]
  },

  // Reebok Collection
  {
    id: 17,
    name: "Reebok Club C 85",
    brand: "Reebok",
    category: "Casual",
    price: 75.99,
    rating: 4.7,
    reviews: 3128,
    color: "White/Green",
    sizes: [6, 7, 8, 9, 10, 11, 12],
    inStock: true,
    discount: 0,
    featured: true,
    image: "https://images.reebok.com/images/club-c-85-white.jpg",
    description: "The Club C 85 is a vintage tennis shoe that brings retro style.",
    material: "Leather",
    weight: "350g",
    releaseDate: "2023-04-03",
    tags: ["tennis", "vintage", "leather"]
  },
  {
    id: 18,
    name: "Reebok Classic Leather",
    brand: "Reebok",
    category: "Casual",
    price: 70.99,
    rating: 4.6,
    reviews: 2678,
    color: "White/Red",
    sizes: [7, 8, 9, 10, 11, 12],
    inStock: true,
    discount: 10,
    featured: false,
    image: "https://images.reebok.com/images/classic-leather-white.jpg",
    description: "The Classic Leather is a timeless silhouette that offers comfort and style.",
    material: "Leather",
    weight: "340g",
    releaseDate: "2023-07-11",
    tags: ["classic", "leather", "retro"]
  },

  // Converse Collection
  {
    id: 19,
    name: "Converse Chuck Taylor All Star",
    brand: "Converse",
    category: "Casual",
    price: 55.99,
    rating: 4.8,
    reviews: 15678,
    color: "Black",
    sizes: [4, 5, 6, 7, 8, 9, 10, 11, 12, 13],
    inStock: true,
    discount: 0,
    featured: true,
    image: "https://images.converse.com/images/chuck-taylor-all-star-black.jpg",
    description: "The Chuck Taylor All Star is the most iconic sneaker of all time.",
    material: "Canvas",
    weight: "300g",
    releaseDate: "2023-01-01",
    tags: ["canvas", "iconic", "high-top"]
  },
  {
    id: 20,
    name: "Converse Chuck 70",
    brand: "Converse",
    category: "Casual",
    price: 85.99,
    rating: 4.9,
    reviews: 4321,
    color: "Oxblood",
    sizes: [5, 6, 7, 8, 9, 10, 11, 12],
    inStock: true,
    discount: 5,
    featured: true,
    image: "https://images.converse.com/images/chuck-70-oxblood.jpg",
    description: "The Chuck 70 offers premium materials and vintage details.",
    material: "Canvas",
    weight: "320g",
    releaseDate: "2023-08-25",
    tags: ["premium", "vintage", "canvas"]
  },

  // Hoka Collection
  {
    id: 21,
    name: "Hoka Bondi 8",
    brand: "Hoka",
    category: "Running",
    price: 165.99,
    rating: 4.8,
    reviews: 1876,
    color: "White/Blue",
    sizes: [7, 8, 9, 10, 11, 12],
    inStock: true,
    discount: 0,
    featured: true,
    image: "https://images.hoka.com/images/bondi-8-white.jpg",
    description: "The Bondi 8 offers maximum cushioning for a smooth ride.",
    material: "Mesh/EVA",
    weight: "290g",
    releaseDate: "2023-06-20",
    tags: ["max-cushion", "running", "comfort"]
  },

  // Saucony Collection
  {
    id: 22,
    name: "Saucony Jazz Court",
    brand: "Saucony",
    category: "Lifestyle",
    price: 80.99,
    rating: 4.5,
    reviews: 987,
    color: "Grey/Blue",
    sizes: [8, 9, 10, 11],
    inStock: true,
    discount: 20,
    featured: false,
    image: "https://images.saucony.com/images/jazz-court-grey.jpg",
    description: "The Jazz Court brings vintage court style to everyday wear.",
    material: "Suede/Leather",
    weight: "360g",
    releaseDate: "2023-10-30",
    tags: ["vintage", "court", "suede"]
  },

  // Limited Editions
  {
    id: 23,
    name: "Nike Dunk Low Retro",
    brand: "Nike",
    category: "Basketball",
    price: 120.99,
    rating: 4.8,
    reviews: 3245,
    color: "University Red/White",
    sizes: [7, 8, 9, 10, 11, 12],
    inStock: false,
    discount: 0,
    featured: true,
    image: "https://static.nike.com/a/images/t_PDP_864_v1/f_auto,b_rgb:f5f5f5/dunk-low-retro-shoes.png",
    description: "The Dunk Low Retro returns with classic color blocking and hoops style.",
    material: "Leather",
    weight: "380g",
    releaseDate: "2023-11-15",
    tags: ["dunk", "retro", "limited"]
  },
  {
    id: 24,
    name: "Yeezy Boost 350 V2",
    brand: "Adidas",
    category: "Lifestyle",
    price: 230.99,
    rating: 4.7,
    reviews: 5672,
    color: "Oreo",
    sizes: [8, 9, 10, 11, 12],
    inStock: false,
    discount: 0,
    featured: true,
    image: "https://assets.adidas.com/images/yeezy-boost-350-v2-oreo.jpg",
    description: "The Yeezy Boost 350 V2 features a Primeknit upper and Boost cushioning.",
    material: "Primeknit/Boost",
    weight: "350g",
    releaseDate: "2023-12-01",
    tags: ["yeezy", "boost", "limited"]
  }
]

// Helper functions to work with the data
const shoeHelpers = {
  // Get unique brands
  getBrands: () => [...new Set(shoes.map(shoe => shoe.brand))],
  
  // Get unique categories
  getCategories: () => [...new Set(shoes.map(shoe => shoe.category))],
  
  // Filter by brand
  filterByBrand: (brand) => shoes.filter(shoe => shoe.brand === brand),
  
  // Filter by price range
  filterByPrice: (min, max) => shoes.filter(shoe => shoe.price >= min && shoe.price <= max),
  
  // Get in-stock shoes
  getInStock: () => shoes.filter(shoe => shoe.inStock),
  
  // Get featured shoes
  getFeatured: () => shoes.filter(shoe => shoe.featured),
  
  // Search by name or description
  search: (query) => shoes.filter(shoe => 
    shoe.name.toLowerCase().includes(query.toLowerCase()) || 
    shoe.description.toLowerCase().includes(query.toLowerCase())
  ),
  
  // Get shoes by size
  filterBySize: (size) => shoes.filter(shoe => shoe.sizes.includes(size)),
  
  // Sort by price (low to high)
  sortByPriceAsc: () => [...shoes].sort((a, b) => a.price - b.price),
  
  // Sort by rating
  sortByRating: () => [...shoes].sort((a, b) => b.rating - a.rating)
}

export { shoes, shoeHelpers }